ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

baseurl = "https://www.ndiquattro.me/"
theme = "cocoa-eh-hugo-theme"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Nick DiQuattro"
title = "Nicholas DiQuattro"
disqusshortname = ""
pluralizelisttitles = false
disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  page = ["HTML", "RSS"]

[permalinks]
blog = "blog/:year/:month/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Example blog"
copyright = "Copyright © 2019-{year} Nicholas DiQuattro"
# copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile = "img/logo.png"
faviconfile = "img/logo.png"
highlightjs = true
highlightjsStyle = "Solarized Light"
progressively = true
share = true
# Share to googleplus, twitter, fb, linkedin by default
# disable by setting share_on_<social network> = false
# example: share_on_googleplus = false
latestpostcount = 5
github = "ndiquattro"
#email = ""
linkedin = "ndiquattro"
twitter = "ndiquattro"
stackoverflow = "3539631"
#facebook = "facebook_id"
#instagram = "instagram_id"
#untappd = "untappd_id"
#itch_io = "itch_io_id"
social_banner = "img/logo.png"
usesmallsummarycard = true
posts_navigation = true
# issoHost = "comments.domain.tld:1234"
githubRepo = "ndiquattro/website/tree/master"
small_banner_logo = false

[params.utteranc]
enable = true
repo = "ndiquattro/website"
issueTerm = "web_comment"

[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"
